# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qfpn_E2LgPXdk76Rd2i76RvRk3DSM3x9
"""



from sqlalchemy import create_engine, text
import pandas as pd


DB_CONNECTION = "postgresql://postgres.qnyrcvrnhtzzkypsrfls:qomkag-3xyPca-gupder@aws-1-us-east-1.pooler.supabase.com:5432/postgres"


engine = create_engine(DB_CONNECTION)


try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT version()"))
        print("✅ Connection successful!")
        print(f"PostgreSQL version: {result.fetchone()[0]}")
except Exception as e:
    print(f"❌ Connection error: {e}")

from sqlalchemy import text

create_tables_sql = """
-- Trains table
CREATE TABLE IF NOT EXISTS trains (
    train_id SERIAL PRIMARY KEY,
    train_number VARCHAR(20) NOT NULL,
    direction VARCHAR(10),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sensors table
CREATE TABLE IF NOT EXISTS sensors (
    sensor_id SERIAL PRIMARY KEY,
    sensor_name VARCHAR(50) NOT NULL,
    track_section VARCHAR(50) NOT NULL,
    sensor_type VARCHAR(30),
    is_active BOOLEAN DEFAULT TRUE
);

-- SACS events table
CREATE TABLE IF NOT EXISTS sensor_events (
    event_id SERIAL PRIMARY KEY,
    event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    train_id INTEGER REFERENCES trains(train_id),
    sensor_id INTEGER REFERENCES sensors(sensor_id),
    track_section VARCHAR(50),
    event_type VARCHAR(20),
    value FLOAT
);

-- Indexes for speed
CREATE INDEX IF NOT EXISTS idx_events_time ON sensor_events(event_time);
CREATE INDEX IF NOT EXISTS idx_events_train ON sensor_events(train_id);
"""

with engine.connect() as conn:
    conn.execute(text(create_tables_sql))  # wrap in text()
    conn.commit()
    print("✅ Tables created")

from sqlalchemy import text


trains_data = [
    ('KTJ-101', 'North'),
    ('KTJ-102', 'South'),
    ('KTJ-103', 'North'),
    ('KTJ-104', 'East')
]

with engine.connect() as conn:
    for train_num, direction in trains_data:

        check = conn.execute(text("SELECT COUNT(*) FROM trains WHERE train_number = :tn"), {"tn": train_num}).scalar()
        if check == 0:
            conn.execute(text("INSERT INTO trains (train_number, direction) VALUES (:tn, :dir)"), {"tn": train_num, "dir": direction})
    conn.commit()
    print("✅ Trains added")


sensors_data = [
    ('Датчик_вход_Алматы1', 'Алматы-1 - Алматы-2', 'entry'),
    ('Датчик_выход_Алматы2', 'Алматы-1 - Алматы-2', 'exit'),
    ('Датчик_вход_Алматы2', 'Алматы-2 - Шелек', 'entry'),
    ('Датчик_выход_Шелек', 'Алматы-2 - Шелек', 'exit')
]

with engine.connect() as conn:
    for name, section, s_type in sensors_data:
        check = conn.execute(text("SELECT COUNT(*) FROM sensors WHERE sensor_name = :sn"), {"sn": name}).scalar()
        if check == 0:
            conn.execute(
                text("INSERT INTO sensors (sensor_name, track_section, sensor_type) VALUES (:name, :section, :type)"),
                {"name": name, "section": section, "type": s_type}
            )
    conn.commit()
    print("✅ Sensors added")

import random
from datetime import datetime, timedelta
from sqlalchemy import text

def generate_train_journey(train_id, track_section, start_time_minutes_ago):
    """Generates entry and exit for one train on the section"""

    entry_time = datetime.now() - timedelta(minutes=start_time_minutes_ago)

    # Normal travel time (60-180 seconds)
    normal_duration = random.uniform(60, 180)

    # Sometimes add a delay (20% probability)
    if random.random() < 0.2:
        normal_duration += random.uniform(120, 300)
        is_delayed = True
    else:
        is_delayed = False

    exit_time = entry_time + timedelta(seconds=normal_duration)

    # Get sensor IDs
    with engine.connect() as conn:
        entry_sensor = conn.execute(
            text("SELECT sensor_id FROM sensors WHERE track_section = :section AND sensor_type = 'entry' LIMIT 1"),
            {"section": track_section}
        ).fetchone()

        exit_sensor = conn.execute(
            text("SELECT sensor_id FROM sensors WHERE track_section = :section AND sensor_type = 'exit' LIMIT 1"),
            {"section": track_section}
        ).fetchone()

    events = [
        (entry_time, train_id, entry_sensor[0], track_section, 'entry', random.uniform(40, 80)),
        (exit_time, train_id, exit_sensor[0], track_section, 'exit', random.uniform(40, 80))
    ]

    return events, normal_duration, is_delayed

# Generate 30 trips
all_events = []
delays_count = 0

for i in range(30):
    train_id = random.randint(1, 4)
    track = random.choice(['Алматы-1 - Алматы-2', 'Алматы-2 - Шелек'])
    minutes_ago = random.randint(1, 120)

    events, duration, is_delayed = generate_train_journey(train_id, track, minutes_ago)
    all_events.extend(events)
    if is_delayed:
        delays_count += 1

# Save to database
with engine.connect() as conn:
    for event in all_events:
        conn.execute(
            text("""
                INSERT INTO sensor_events (event_time, train_id, sensor_id, track_section, event_type, value)
                VALUES (:event_time, :train_id, :sensor_id, :track_section, :event_type, :value)
            """),
            {
                "event_time": event[0],
                "train_id": event[1],
                "sensor_id": event[2],
                "track_section": event[3],
                "event_type": event[4],
                "value": event[5]
            }
        )
    conn.commit()

print(f"✅ Generated {len(all_events)} events (30 trips)")
print(f"⚠️ Of which delays: {delays_count}")

query = """
WITH entry_times AS (
    SELECT
        train_id,
        track_section,
        event_time AS entry_time,
        value AS speed
    FROM sensor_events
    WHERE event_type = 'entry'
),
exit_times AS (
    SELECT
        train_id,
        track_section,
        event_time AS exit_time
    FROM sensor_events
    WHERE event_type = 'exit'
)
SELECT
    e.train_id,
    t.train_number,
    e.track_section,
    e.entry_time,
    x.exit_time,
    EXTRACT(EPOCH FROM (x.exit_time - e.entry_time)) AS duration_seconds,
    e.speed AS entry_speed
FROM entry_times e
JOIN exit_times x
    ON e.train_id = x.train_id AND e.track_section = x.track_section
JOIN trains t ON e.train_id = t.train_id
WHERE x.exit_time > e.entry_time
ORDER BY e.entry_time DESC
"""

df = pd.read_sql(query, engine)
print(f"📊 Analyzed {len(df)} passages\n")
df.head(10)

stats = df.groupby('track_section')['duration_seconds'].agg(['mean', 'std', 'count']).reset_index()
stats.columns = ['track_section', 'mean_seconds', 'std_seconds', 'count_trips']
stats['threshold_anomaly'] = stats['mean_seconds'] + 2 * stats['std_seconds']
stats['threshold_warning'] = stats['mean_seconds'] + stats['std_seconds']


df_analysis = df.merge(stats[['track_section', 'mean_seconds', 'threshold_warning', 'threshold_anomaly']], on='track_section')
df_analysis['status'] = '✅ Normal'


df_analysis.loc[df_analysis['duration_seconds'] > df_analysis['threshold_warning'], 'status'] = '⚠️ Warning'
df_analysis.loc[df_analysis['duration_seconds'] > df_analysis['threshold_anomaly'], 'status'] = '🔴 CRITICAL DELAY'


anomalies = df_analysis[df_analysis['status'] != '✅ Normal']
print(f"\n{'='*60}")
print(f"📊 STATISTICS:")
print(f"   Total trips: {len(df_analysis)}")
print(f"   Normal: {len(df_analysis[df_analysis['status']=='✅ Normal'])}")
print(f"   Warning: {len(df_analysis[df_analysis['status']=='⚠️ Warning'])}")
print(f"   🔴 Critical delays: {len(df_analysis[df_analysis['status']=='🔴 CRITICAL DELAY'])}")
print(f"{'='*60}\n")

if len(anomalies) > 0:
    print("⚠️ Detected problems:")
    anomalies[['train_number', 'track_section', 'duration_seconds', 'mean_seconds', 'status']]
else:
    print("✅ All trips are normal")

anomalies = df_analysis[df_analysis['status'] != '✅ Normal'].copy()

if len(anomalies) > 0:
    print("="*80)
    print("🚨 DETECTED PROBLEMS (full list):")
    print("="*80)


    anomalies['severity'] = anomalies['status'].map({'🔴 CRITICAL DELAY': 0, '⚠️ Warning': 1})
    anomalies = anomalies.sort_values('severity')


    display_cols = ['train_number', 'track_section', 'duration_seconds', 'mean_seconds', 'status']
    display(anomalies[display_cols])

    print("\n" + "="*80)
    print("📊 DETAILED STATISTICS BY ANOMALIES:")
    print("="*80)

    for section in anomalies['track_section'].unique():
        section_anomalies = anomalies[anomalies['track_section'] == section]
        print(f"\n📍 Section: {section}")
        print(f"   - Total problems: {len(section_anomalies)}")
        print(f"   - Of which critical: {len(section_anomalies[section_anomalies['status'] == '🔴 CRITICAL DELAY'])}")
        print(f"   - Average time (normal): {section_anomalies['mean_seconds'].iloc[0]:.1f} sec")
        print(f"   - Maximum delay: {section_anomalies['duration_seconds'].max():.1f} sec")
else:
    print("✅ All trips are normal, no problems detected")

print("\n" + "="*80)
print("✅ EXAMPLES OF NORMAL TRIPS (for comparison):")
print("="*80)

normal_trips = df_analysis[df_analysis['status'] == '✅ Normal'].head(10)
display(normal_trips[['train_number', 'track_section', 'duration_seconds', 'mean_seconds']])

print(f"\n📈 Brief statistics for normal trips:")
print(f"   - Minimum time: {normal_trips['duration_seconds'].min():.1f} sec")
print(f"   - Maximum time: {normal_trips['duration_seconds'].max():.1f} sec")
print(f"   - Average time: {normal_trips['duration_seconds'].mean():.1f} sec")

import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(2, 2, figsize=(16, 12))


ax1 = axes[0, 0]
colors = {'✅ Normal': 'blue', '⚠️ Warning': 'orange', '🔴 CRITICAL DELAY': 'red'}

for status in colors.keys():
    status_data = df_analysis[df_analysis['status'] == status]
    ax1.scatter(status_data['entry_time'], status_data['duration_seconds'],
               c=colors[status], alpha=0.6, s=50, label=status,
               marker='o' if status == '✅ Normal' else '^')

ax1.axhline(y=df_analysis['mean_seconds'].mean(), color='green', linestyle='--', linewidth=2, label='Network average')
ax1.set_xlabel('Entry time to section')
ax1.set_ylabel('Travel time (seconds)')
ax1.set_title('Monitoring of KTZ section travel time')
ax1.legend()
ax1.grid(True, alpha=0.3)


ax2 = axes[0, 1]
sections = stats['track_section']
x = np.arange(len(sections))
width = 0.35

bars1 = ax2.bar(x - width/2, stats['mean_seconds'], width, label='Average time', color='green', alpha=0.7)
bars2 = ax2.bar(x + width/2, stats['threshold_anomaly'], width, label='Anomaly threshold (mean+2σ)', color='red', alpha=0.7)


for bar in bars1:
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height, f'{height:.0f}', ha='center', va='bottom')
for bar in bars2:
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height, f'{height:.0f}', ha='center', va='bottom')

ax2.set_xlabel('Section')
ax2.set_ylabel('Seconds')
ax2.set_title('Comparison of average time with anomaly threshold')
ax2.set_xticks(x)
ax2.set_xticklabels(sections, rotation=15, ha='right')
ax2.legend()
ax2.grid(True, alpha=0.3, axis='y')


ax3 = axes[1, 0]
for section in df_analysis['track_section'].unique():
    section_data = df_analysis[df_analysis['track_section'] == section]
    ax3.hist(section_data['duration_seconds'], alpha=0.5, label=section, bins=15)
ax3.set_xlabel('Travel time (seconds)')
ax3.set_ylabel('Number of trains')
ax3.set_title('Travel time distribution by section')
ax3.legend()
ax3.grid(True, alpha=0.3)


ax4 = axes[1, 1]
problem_counts = anomalies.groupby('track_section').size()
if len(problem_counts) > 0:
    ax4.pie(problem_counts.values, labels=problem_counts.index, autopct='%1.1f%%', startangle=90)
    ax4.set_title('Problem distribution by section')
else:
    ax4.text(0.5, 0.5, 'No problems', ha='center', va='center', fontsize=20)
    ax4.set_title('Problem distribution by section')

plt.tight_layout()
plt.show()


print("\n" + "="*80)
print("📊 KEY FINDINGS FROM ANALYSIS RESULTS:")
print("="*80)
print(f"1. Total trains analyzed: {len(df_analysis)}")
print(f"2. Percentage of anomalies: {len(anomalies)/len(df_analysis)*100:.1f}%")
print(f"3. Critical delays: {len(anomalies[anomalies['status']=='🔴 CRITICAL DELAY'])}")
print(f"4. Most problematic section: {anomalies['track_section'].mode()[0] if len(anomalies)>0 else 'none'}")

from sqlalchemy import text
from datetime import datetime


df_analysis['detected_at'] = datetime.now()


with engine.connect() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS detected_anomalies (
            id SERIAL PRIMARY KEY,
            train_id INTEGER,
            track_section VARCHAR(50),
            duration_seconds FLOAT,
            mean_seconds FLOAT,
            status VARCHAR(50),
            detected_at TIMESTAMPTZ
        )
    """))
    conn.commit()
    print("✅ Table detected_anomalies created (or already exists)")


critical_to_save = df_analysis[df_analysis['status'] == '🔴 CRITICAL DELAY']

if len(critical_to_save) > 0:
    with engine.connect() as conn:
        for _, row in critical_to_save.iterrows():
            conn.execute(text("""
                INSERT INTO detected_anomalies (train_id, track_section, duration_seconds, mean_seconds, status, detected_at)
                VALUES (:train_id, :track_section, :duration_seconds, :mean_seconds, :status, :detected_at)
            """), {
                "train_id": int(row['train_id']),
                "track_section": row['track_section'],
                "duration_seconds": float(row['duration_seconds']),
                "mean_seconds": float(row['mean_seconds']),
                "status": 'critical',
                "detected_at": row['detected_at']
            })
        conn.commit()
    print(f"✅ Saved {len(critical_to_save)} anomalies to detected_anomalies table")


    print("\n📝 Saved critical delays:")
    display(critical_to_save[['train_number', 'track_section', 'duration_seconds', 'mean_seconds']])
else:
    print("ℹ️ No critical delays to save")


print("\n" + "="*60)
print("📋 Contents of detected_anomalies table:")
print("="*60)

try:
    df_anomalies_db = pd.read_sql("SELECT * FROM detected_anomalies ORDER BY detected_at DESC", engine)
    if len(df_anomalies_db) > 0:
        display(df_anomalies_db)
    else:
        print("Table is empty")
except Exception as e:
    print(f"Error reading table: {e}")
